<h3>Gerência de Produtos</h3>

<p><a href="<?php echo $this->url(
    array(
        'controller' => 'produto',
        'action'     => 'adicionar'
    ),
    'default',
    true) ?>">Adicionar um novo produto</a></p>
 
Produtos cadastrados: <br />
<dl>
    <?php foreach ($this->produtos as $produto): ?>
	<dt>Nome: 
		<a href="<?php echo $this->url(array('controller' => 'produto', 'action' => 'editar', 'id' => $produto->getId())); ?>">
			<?php echo $this->escape($produto->getNome()) ?>
		</a>
	</dt>
    <dd>Preço: <?php echo $this->escape($produto->getPreco()) ?></dd>
    <dd>Qtd: <?php echo $this->escape($produto->getEstoque()) ?></dd>
    <dd>Nivel crítico: <?php echo $this->escape($produto->getCriticidade()) ?></dd>
    <dd>Fornecedor: <?php echo $this->escape($produto->getFornecedor()) ?></dd>
    <?php endforeach ?>
</dl>

<?php if ($this->criticos != null) : ?>
	<div id="atencao">
		<p style="color:red;">Atenção: os <?php echo count($this->criticos) ?> produtos seguintes estão em nível crítico:</p>
		
		<ul>
		<?php foreach ($this->criticos as $produto): ?>
			<li class="critico"><?php echo $produto->getNome() . ' - Quantidade: ' . $produto->getEstoque() . ', Nível Crítico: ' . $produto->getCriticidade() ?></li>
		<?php endforeach; ?>
		</ul>
	</div>
<?php endif; ?>
