<h3>Gerência de Usuários</h3>
<div id="tabela">
	<table class="listagem">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Login</th>
				<th>Data de Inserção</th>
				<th>Data de Nascimento</th>
				<th>Excluir</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->usuarios as $usuario): ?>
			<tr>
				<td><a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'editar', 'id' => $usuario->getId())); ?>">
					<?php echo $this->escape($usuario->getNome()) ?></a></td>
				<td class="centro"><?php echo $this->escape($usuario->getNomeUsuario()) ?></td>
				<td class="centro"><?php echo $this->escape($usuario->getInsercao()) ?></td>
				<td class="centro"><?php echo $this->escape($usuario->getDataNascimento()) ?></td>
				<td class="centro"><a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'excluir', 'id' => $usuario->getId())); ?>">X</a></td>
			</tr>
			<?php endforeach ?>
			<tr>
				<td colspan="7" style="text-align:right"><a href="<?php echo $this->url(
					array(
						'controller' => 'usuario',
						'action'     => 'adicionar'
					),
					'default',
					true) ?>">Adicionar um novo usuário</a></td>
			</tr>
		</tbody>
	</table>
</div>
